### ISSUE TITLE
cli createApp Unhandled Rejection

### ISSUE THREAD

**Issue by mattvb91** [corejam/corejam#185]
Latest release throws following error. How do we catch these cases in our pipeline?

`
npx @corejam/cli createApp test
`

`
⠋ Moving words aroundUnhandled Rejection at: Promise Promise {
  <rejected> Error: Path to move doesn't exist test/server/resolvers/db/faker/pluginName.ts
      at generateSourceDoesntExistError (_npx/5619/lib/node_modules/@corejam/cli/node_modules/fs-jetpack/lib/move.js:32:15)
      at _npx/5619/lib/node_modules/@corejam/cli/node_modules/fs-jetpack/lib/move.js:137:28 {
    code: 'ENOENT'
  }
}
`

Also the output is: 
```
✔ Templates finished
✔ Copy finished
```

but ls -lah results: 

```
README.md	package.json
```

So it didn't actually do the copy

**Comment by mattvb91** [comment]
the template dir was missing in the npm release due to recursive package.jsons, had to rename to _package.json and copy during create to fix it,
